### ISSUE TITLE
Useless makedepend wget

### ISSUE THREAD

**Issue by stepanse** [tkmxqrdxddd/chess-electron#1]
In the PKGBUILD, there is, on line 10
> `makedepends=('wget')`

Since wget is not used anywhere else in the PKGBUILD, it is not necessary as a makedepend.

**Comment by tkmxqrdxddd** [comment]
do it yourself

**Comment by tkmxqrdxddd** [comment]
idc

**Comment by tkmxqrdxddd** [comment]
Don't care fix it youself

**Comment by tkmxqrdxddd** [comment]
Don't care fix it youself
